// <auto-generated />
using System;
using ClienteCRUD.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace crud_clientes.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240928113814_CliMigration")]
    partial class CliMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ClienteCRUD.Models.Cliente", b =>
                {
                    b.Property<int>("CLI_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CLI_ID"));

                    b.Property<bool>("CLI_ATIVO")
                        .HasColumnType("bit");

                    b.Property<DateTime>("CLI_DATANASCIMENTO")
                        .HasColumnType("datetime2");

                    b.Property<string>("CLI_NOME")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("CLI_ID");

                    b.ToTable("Clientes");
                });
#pragma warning restore 612, 618
        }
    }
}
